# src/utils/latex_utils.py

"""
Utility functions and mappings for LaTeX symbol handling.
"""

# Mapping from parameter keys to LaTeX symbols
LATEX_KEY_MAP = {
    # Greek Letters (Lowercase)
    'alpha': r'\alpha',
    'beta': r'\beta',
    'gamma': r'\gamma',
    'delta': r'\delta',
    'epsilon': r'\epsilon',
    'zeta': r'\zeta',
    'eta': r'\eta',
    'theta': r'\theta',
    'iota': r'\iota',
    'kappa': r'\kappa',
    'lambda': r'\lambda',
    'lambda_param': r'\lambda',
    'mu': r'\mu',
    'nu': r'\nu',
    'xi': r'\xi',
    'omicron': r'o',
    'pi': r'\pi',
    'rho': r'\rho',
    'sigma': r'\sigma',
    'tau': r'\tau',
    'upsilon': r'\upsilon',
    'phi': r'\phi',
    'chi': r'\chi',
    'psi': r'\psi',
    'omega': r'\omega',

    # Greek Letters (Uppercase)
    'Gamma': r'\Gamma',
    'Delta': r'\Delta',
    'Theta': r'\Theta',
    'Lambda': r'\Lambda',
    'Xi': r'\Xi',
    'Pi': r'\Pi',
    'Sigma': r'\Sigma',
    'Upsilon': r'\Upsilon',
    'Phi': r'\Phi',
    'Psi': r'\Psi',
    'Omega': r'\Omega',

    # Latin Letters (Lowercase)
    'a': r'a',
    'b': r'b',
    'c': r'c',
    'd': r'd',
    'e': r'e',
    'f': r'f',
    'g': r'g',
    'h': r'h',
    'i': r'i',
    'j': r'j',
    'k': r'k',
    'l': r'l',
    'm': r'm',
    'n': r'n',
    'o': r'o',
    'p': r'p',
    'q': r'q',
    'r': r'r',
    's': r's',
    't': r't',
    'u': r'u',
    'v': r'v',
    'w': r'w',
    'x': r'x',
    'y': r'y',
    'z': r'z',

    # Latin Letters (Uppercase)
    'A': r'A',
    'B': r'B',
    'C': r'C',
    'D': r'D',
    'E': r'E',
    'F': r'F',
    'G': r'G',
    'H': r'H',
    'I': r'I',
    'J': r'J',
    'K': r'K',
    'L': r'L',
    'M': r'M',
    'N': r'N',
    'O': r'O',
    'P': r'P',
    'Q': r'Q',
    'R': r'R',
    'S': r'S',
    'T': r'T',
    'U': r'U',
    'V': r'V',
    'W': r'W',
    'X': r'X',
    'Y': r'Y',
    'Z': r'Z',

    # Common Mathematical Symbols
    'sum': r'\sum',
    'prod': r'\prod',
    'int': r'\int',
    'infty': r'\infty',
    'partial': r'\partial',
    'nabla': r'\nabla',
    'approx': r'\approx',
    'equiv': r'\equiv',
    'neq': r'\neq',
    'leq': r'\leq',
    'geq': r'\geq',
    'subset': r'\subset',
    'supset': r'\supset',
    'subseteq': r'\subseteq',
    'supseteq': r'\supseteq',
    'times': r'\times',
    'cdot': r'\cdot',
    'rightarrow': r'\rightarrow',
    'leftarrow': r'\leftarrow',
    'leftrightarrow': r'\leftrightarrow',
    'Rightarrow': r'\Rightarrow',
    'Leftarrow': r'\Leftarrow',
    'Leftrightarrow': r'\Leftrightarrow',
    'forall': r'\forall',
    'exists': r'\exists',
    'in': r'\in',
    'notin': r'\notin',
    'ni': r'\ni',
    'cap': r'\cap',
    'cup': r'\cup',
    'vee': r'\vee',
    'wedge': r'\wedge',
    'oplus': r'\oplus',
    'otimes': r'\otimes',
    'circ': r'\circ',
    'bullet': r'\bullet',
    'star': r'\star',
    'dagger': r'\dagger',
    'ddagger': r'\ddagger',
    'diamond': r'\diamond',
    'ast': r'\ast',
    'amalg': r'\amalg',

    # Subscripts and Superscripts
    'sub': r'_',
    'sup': r'^',

    # Fractions and Roots
    'frac': r'\frac',
    'sqrt': r'\sqrt',

    # Other Symbols
    'neq': r'\neq',
    'leftharpoonup': r'\leftharpoonup',
    'rightharpoonup': r'\rightharpoonup',
    'leftrightharpoons': r'\leftrightharpoons',
    'Rightarrow': r'\Rightarrow',

    # Add more mappings as needed
}
